
version: 1

update_configs:
  - directory: "/Resources/NetHookAnalyzer2"
    package_manager: "dotnet:nuget"
    update_schedule: "live"

  - directory: "/Samples"
    package_manager: "dotnet:nuget"
    update_schedule: "live"

  - directory: "/SteamKit2"
    package_manager: "dotnet:nuget"
    update_schedule: "live"
